### ISSUE TITLE
Review HTTP500 issues in production

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/Core#146]
![image](https://user-images.githubusercontent.com/749833/215642694-57939e49-2452-4a07-ae5c-2668d8f60373.png)

**Comment by dmugtasimov** [comment]
```
2023-01-28 07:40:59,405 ERROR django.request Internal Server Error: /api/blocks
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  sorry, too many clients already


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 78, in inner
    with self._recreate_cm():
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/transaction.py", line 197, in __enter__
    if not connection.get_autocommit():
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 455, in get_autocommit
    self.ensure_connection()
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/root/.cache/pypoetry/virtualenvs/core-gHi8t1rX-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  sorry, too many clients already

172.18.0.6:56922 - - [28/Jan/2023:07:40:59] "POST /api/blocks" 500 145
```

**Comment by dmugtasimov** [comment]
https://forum.djangoproject.com/t/when-are-db-connections-closed/16347/11

```
[apollo13](https://forum.djangoproject.com/u/apollo13)
[Oct '22](https://forum.djangoproject.com/t/when-are-db-connections-closed/16347/11)
Hi,

Daphne & Channels doesn’t close connections yet by “design” (there is an open ticket for it). Basically in Daphne you get a new “thread” (not exactly but a new async context) and that counts as “thread” as far as Django is concerned. Due to that Django will never reuse such a “thread” and as such connections with a max age > 0 are never closed. To fix this we need to implement a connection pool in Django.

Cheers,
Florian
```

This also validates with the research I have made myself

**Comment by dmugtasimov** [comment]
Fix suggestions are too DevOpsy:

```
[Oct '22](https://forum.djangoproject.com/t/when-are-db-connections-closed/16347/17)
Well make sure CONN_MAX_AGE is set to 0, this will close connections at the end of the request. Then add a pgbouncer/pgpool to reduce the load of connection creation on the db server.
```

**Comment by dmugtasimov** [comment]
@buckyroberts this should fix the issue: https://github.com/thenewboston-developers/Core/pull/148

**Comment by dmugtasimov** [comment]
Fix of the issue: https://github.com/thenewboston-developers/Core/pull/148
Fix of CI issues:
- https://github.com/thenewboston-developers/Core/pull/149
- https://github.com/thenewboston-developers/Core/pull/150
- https://github.com/thenewboston-developers/Core/pull/151
